### ISSUE TITLE
A little question about the code

### ISSUE THREAD

**Issue by SuperYFan** [swsamleo/MLSTGCN#1]
Hello author, I want to know why the code will be 5 graph Embedding only took the data of the first column, in this case is not the other information are discarded?
Why does the graph take W[:, :, 0]?
![image](https://user-images.githubusercontent.com/117325719/199631227-9450f16e-f791-41ba-b8bd-c36d78e3c8b9.png)

**Comment by swsamleo** [comment]
There is already enough contextual information. Embedding is mainly to help train, in this experiment, the first column is enough to obtain a good result. If you want to use all the information, then you can go through some fully-connected layers to get the new embedding.

**Comment by SuperYFan** [comment]
Thank you for your reply!
